# Generated by Django 2.1.5 on 2019-01-27 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('body', models.TextField(verbose_name='本文')),
                ('is_done', models.BooleanField(verbose_name='完了したか')),
            ],
        ),
    ]
